version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/auth"
    update_schedule: "live"
  - package_manager: "javascript"
    directory: "/client"
    update_schedule: "live"
  - package_manager: "javascript"
    directory: "/common"
    update_schedule: "live"
  - package_manager: "javascript"
    directory: "/expiration"
    update_schedule: "live"
  - package_manager: "javascript"
    directory: "/orders"
    update_schedule: "live"
  - package_manager: "javascript"
    directory: "/payments"
    update_schedule: "live"
  - package_manager: "javascript"
    directory: "/tickets"
    update_schedule: "live"